### ISSUE TITLE
It’s crashing my Amd GPU and restarts pc

### ISSUE THREAD

**Issue by Tmarsh87** [Albermonte/NIM-Pools-Hub-Miner#37]
When I try to run it on my 4g amd gpu it will run for a little while then it will crash the driver and restart the pc. I have updated the drive and it still crashes. I'm just guessing my older gpu is not supposed.

**Comment by arminiowski** [comment]
do not do that

**Comment by Albermonte** [comment]
Or your GPU is not supported because it's too old or your GPU is crashing due to temperatures being too high. Look for the tempreatures, check your GPU parameters and make sure there's nothing wrong there.

Make sure you didn't overclock the VRAM or the frequencies that can also cause some crashes under high load.
